version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sales_order_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: sales_order_db
volumes:
  db-data:

